from resources.heroes.Adventurer import *
from resources.heroes.Knight import *
from resources.heroes.Thief import *
from resources.heroes.Healer import *
from resources.heroes.AngryGrandmother import *
from resources.heroes.AppleFanboy import *
from resources.heroes.Dragon import *
from resources.heroes.Nerd import *
from resources.heroes.Tank import *
from resources.heroes.Error404 import *
