from resources.environment.castle import *
from resources.environment.gravel import *
from resources.environment.groundGreen import *
from resources.environment.groundStone import *
from resources.environment.groundWood import *
from resources.environment.house import *
from resources.environment.totenkopf import *
from resources.environment.wallGreen import *
from resources.environment.wallStone import *
from resources.environment.wallWood import *