from resources.Environment.castle import *
from resources.Environment.gravel import *
from resources.Environment.groundGreen import *
from resources.Environment.groundStone import *
from resources.Environment.groundWood import *
from resources.Environment.house import *
from resources.Environment.totenkopf import *
from resources.Environment.wallGreen import *
from resources.Environment.wallStone import *
from resources.Environment.wallWood import *